#!/usr/bin/env bash

   file=$1
   file_name="${file##*/}"
   convert_file=`echo "$file" | sed 's/\.\w*$/ (flipped horizontally).mp4/'`

   (ffmpeg -i "$file" -crf 18 -vf hflip -c:a copy "$convert_file") | zenity --progress --confirm-overwrite --pulsate --auto-close --title="Flipping..." --text="Flipping ""$file_name""" &

PID_ZENITY=${!}
PID_CHILD=$(pgrep -o -P $$)
export PID_FFMPEG=`jobs -p`

while [ "$PID_ZENITY" != "" ]
do
  PID_TASKS=$(pgrep -d ' ' -P ${PID_CHILD})
  PID_ZENITY=$(ps h -o pid --pid ${PID_ZENITY} | xargs)
  sleep 2
done

kill -9 "$PID_FFMPEG"

[ "${PID_TASKS}" != "" ] && kill -9 ${PID_TASKS}

   shift
done
