#!/usr/bin/env bash

   file=$1
   file_name="${file##*/}"
   convert_file=`echo "$file" | sed 's/\.\w*$/ (custom speed).mp4/'`
   temp_file=`echo "$file" | sed 's/\.\w*$/ (temp).h264/'`
   frate=$(ffmpeg -i "$file" 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p")
   custom_rate=$(zenity --entry --title "New speed" --text "Please enter the speed you want to multiply by (e.g. 0.2, 1.5, 3, etc.)")
   newrate=$(echo "$frate $custom_rate" | awk '{print $1 * $2}')

if test -f "$convert_file"; then   
   (zenity --question --text="$convert_file already exists. Overwrite it?"
      if [ $? = 1 ]; then
      kill -9 $$
   else
      rm "$convert_file"
   fi)
fi

ffmpeg -i "$file" -map 0:v -c:v copy -bsf:v h264_mp4toannexb "$temp_file";
ffmpeg -fflags +genpts -r "$newrate" -i "$temp_file" -c:v copy "$convert_file" | zenity --progress --confirm-overwrite --pulsate --auto-close --title="Increasing speed..." --text="Increasing speed of ""$file_name""" &

PID_ZENITY=${!}
PID_CHILD=$(pgrep -o -P $$)
export PID_FFMPEG=`jobs -p`

while [ "$PID_ZENITY" != "" ]
do
  PID_TASKS=$(pgrep -d ' ' -P ${PID_CHILD})
  PID_ZENITY=$(ps h -o pid --pid ${PID_ZENITY} | xargs)
  sleep 2
done

kill -9 "$PID_FFMPEG"

[ "${PID_TASKS}" != "" ] && kill -9 ${PID_TASKS}

rm "$temp_file"
   shift
done
