#!/usr/bin/env bash

   file="$1"
   file_name="${file##*/}"
   convert_file=`echo "$file" | sed 's/\.\w*$/ (loop).mp4/'`

if test -f "$convert_file"; then   
   (zenity --question --text="$convert_file already exists. Overwrite it?"
      if [ $? = 1 ]; then
      kill -9 $$
   else
      rm "$convert_file"
   fi)
fi

  nloop=$(zenity --entry --title "Number of loops" --text "Please enter the number of times you want the video to loop.")

ffmpeg -stream_loop "$nloop" -i "$file" -c copy "$convert_file" | zenity --progress --confirm-overwrite --pulsate --auto-close --title="Looping" --text="Looping..." &

PID_ZENITY=${!}
PID_CHILD=$(pgrep -o -P $$)
export PID_FFMPEG=`jobs -p`

while [ "$PID_ZENITY" != "" ]
do
  PID_TASKS=$(pgrep -d ' ' -P ${PID_CHILD})
  PID_ZENITY=$(ps h -o pid --pid ${PID_ZENITY} | xargs)
  sleep 2
done

kill -9 "$PID_FFMPEG"

[ "${PID_TASKS}" != "" ] && kill -9 ${PID_TASKS}

   shift
done

