#!/usr/bin/env bash
   file=$1
   convert_file=`echo "$file" | sed 's/\.\w*$/ (audio added).mp4/'`
   audio_file=$(zenity --file-selection --title="Select the audio track you want to add")

   (ffmpeg -i "$file" -i "$audio_file" -c copy -map 0:v:0 -map 1:a:0 "$convert_file") | zenity --progress --pulsate --title="Removing audio" --auto-close --text="Removing audio..." &

PID_ZENITY=${!}
PID_CHILD=$(pgrep -o -P $$)
export PID_FFMPEG=`jobs -p`

while [ "$PID_ZENITY" != "" ]
do
  PID_TASKS=$(pgrep -d ' ' -P ${PID_CHILD})
  PID_ZENITY=$(ps h -o pid --pid ${PID_ZENITY} | xargs)
  sleep 2
done

kill -9 "$PID_FFMPEG"

[ "${PID_TASKS}" != "" ] && kill -9 ${PID_TASKS}

   shift
done
